# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alncat's Personal Site
email: zhenwei.luo@rice.edu
description: > # this means to ignore newlines until "baseurl:"
    I am a graduate student in Rice University's Applied Physics program.
    My current research is mainly about developing novel crystallographic 
    methods. In spare time, I am an android developer, an artificial intelligence learner and an algorithm designer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alncat.github.io" # the base hostname & protocol for your site
twitter_username: tlzw
github_username:  alncat

# Build settings
markdown: kramdown
